export const logoDarkPath = '/assets/joat_logo_dark.png'
export const logoLightPath = '/assets/joat_logo_light.svg'
export const landingStarsPath = '/assets/landing_page_bg_stars.svg'
export const questionStarsPath = '/assets/question_page_bg_stars.svg'
export const resultStarsPath = '/assets/bg_star.svg'
export const backArrowPath = '/assets/back_arrow.svg'
export const forwardArrowPath = '/assets/forward_arrow.svg'
export const beginButtonImage = '/assets/begin_button.svg'
