export const logoDarkPath = '/storage/assets/joat_logo_dark.png'
export const logoLightPath = '/storage/assets/joat_logo_light.svg'
export const landingStarsPath = '/storage/assets/landing_page_bg_stars.svg'
export const questionStarsPath = '/storage/assets/question_page_bg_stars.svg'
export const resultStarsPath = '/storage/assets/bg_star.svg'
export const backArrowPath = '/storage/assets/back_arrow.svg'
export const forwardArrowPath = '/storage/assets/forward_arrow.svg'
