const option = (key, text, score) => ({
  key,
  text,
  score,
})

export const categories = [
  { id: 'engagement_pattern', label: 'Engagement Pattern', color: '#69B2F5' },
  { id: 'education', label: 'Education & Credentials', color: '#F4BE21' },
  { id: 'decision_drivers', label: 'Decision Drivers', color: '#A9D90A' },
  { id: 'regret_reflection', label: 'Regret & Reflection', color: '#F8453D' },
  { id: 'identity_self_perception', label: 'Identity & Self-Perception', color: '#FF5A2C' },
  { id: 'agency_energy', label: 'Agency & Energy', color: '#9B21F0' },
]

export const questions = [
  {
    id: 'ep_q1',
    category: 'engagement_pattern',
    text: 'When you pick up a new interest, what typically happens?',
    options: [
      option('A', 'I explore it deeply for months or years before considering anything else.', 1),
      option('B', 'I learn enough to understand how it works, then move on to something new.', 3),
      option('C', 'I juggle several interests at once, rotating between them as energy shifts.', 4),
      option('D', 'I explore widely but keep returning to one core skill to deepen it.', 2),
      option('E', 'I start many things but rarely finish or consolidate any of them.', 5),
    ],
  },
  {
    id: 'ep_q2',
    category: 'engagement_pattern',
    text: "How do you know when you've 'learned' something new?",
    options: [
      option('A', 'When I can perform it at a level where others would pay me or hire me.', 1),
      option('B', 'When I understand the underlying principles well enough to explain them.', 2),
      option('C', "When I've solved the puzzle of how it works, even if I never apply it again.", 4),
      option('D', 'When I can combine it with something else I already know in a useful way.', 3),
      option('E', "I rarely feel like I've truly 'learned' anything\u2014I just keep accumulating.", 5),
    ],
  },
  {
    id: 'ep_q3',
    category: 'engagement_pattern',
    text: 'Look at the past 5 years. How many distinct skill areas have you invested meaningful time in?',
    options: [
      option('A', 'One primary area. Everything else is casual or supportive.', 1),
      option('B', 'Two to three areas that I take seriously, even if one dominates.', 2),
      option('C', "Four to six areas that I actively practice and don't want to drop.", 3),
      option('D', "More than six. I can't easily list them because they blur together.", 4),
      option('E', 'I start many but only one or two ever reach a meaningful level.', 5),
    ],
  },
  {
    id: 'ec_q1',
    category: 'education',
    text: 'How important is formal certification or institutional validation for the work you do?',
    options: [
      option('A', "Essential. I won't pursue something seriously without a credential path.", 1),
      option('B', "Useful but not necessary. I respect credentials but don't wait for them.", 2),
      option('C', 'Mostly irrelevant. I prove capability through work, not paper.', 3),
      option('D', 'Actively avoided. Credentials feel like gates that exclude people like me.', 4),
      option('E', "I don't think about this much\u2014I just do what interests me.", 3),
    ],
  },
  {
    id: 'ec_q2',
    category: 'education',
    text: 'How do you currently demonstrate your skills to others?',
    options: [
      option('A', 'Through formal qualifications, job titles, or institutional affiliations.', 1),
      option('B', 'Through a portfolio, published work, or public projects people can see.', 2),
      option('C', 'Through word of mouth or informal networks\u2014people know what I can do.', 3),
      option('D', "I mostly don't. My skills are private or I struggle to show them publicly.", 5),
      option('E', "I share work-in-progress openly, even when it's unfinished or experimental.", 4),
    ],
  },
  {
    id: 'ec_q3',
    category: 'education',
    text: 'Have you ever abandoned a skill path because it lacked a clear credential or career ladder?',
    options: [
      option('A', 'Yes, multiple times. I need external structure to justify deep investment.', 1),
      option('B', 'Once or twice. I felt the pressure but sometimes pushed through anyway.', 2),
      option('C', 'No. I pursue what interests me and figure out validation later.', 3),
      option('D', 'I actively avoid credential-heavy paths because they feel restrictive.', 4),
      option('E', "I haven't had to choose\u2014my path already had credentials built in.", 1),
    ],
  },
  {
    id: 'dd_q1',
    category: 'decision_drivers',
    text: 'When you make a major life decision (career, education, relocation), what guides you most?',
    options: [
      option('A', 'Security and stability. Predictable outcomes matter most.', 1),
      option('B', 'A single passionate interest that I want to pursue fully.', 2),
      option('C', 'How the choice connects or enables my other interests.', 3),
      option('D', "Curiosity and novelty. I follow what feels alive, even if it's risky.", 4),
      option('E', 'External expectations\u2014family, culture, or what seems respectable.', 1),
    ],
  },
  {
    id: 'dd_q2',
    category: 'decision_drivers',
    text: 'You have a free weekend with no obligations. What do you actually do?',
    options: [
      option('A', 'Rest or socialize. I need recovery from structured work.', 2),
      option('B', 'Work on a specific project with a deadline or goal.', 1),
      option('C', 'Explore something new\u2014read, watch, tinker without a deliverable.', 4),
      option('D', 'Work on a personal project that combines several of my interests.', 3),
      option('E', 'I feel conflicted\u2014there are too many things I want to do and I end up doing little.', 5),
    ],
  },
  {
    id: 'dd_q3',
    category: 'decision_drivers',
    text: 'Do your different skills ever actively help each other, or do they stay separate?',
    options: [
      option('A', "They stay separate. I switch contexts but they don't really interact.", 1),
      option('B', 'Occasionally. A skill from one area unexpectedly solves a problem in another.', 2),
      option('C', 'Frequently. I deliberately apply frameworks from one domain to another.', 3),
      option('D', 'My skills have merged into a single approach I use across everything.', 4),
      option('E', "I don't have enough developed skills for this question to apply.", 5),
    ],
  },
  {
    id: 'rr_q1',
    category: 'regret_reflection',
    text: "Looking back at choices you've made, what do you most often feel?",
    options: [
      option('A', 'Satisfied. I committed to a path and it was the right call.', 1),
      option('B', "Curious. I wonder what would have happened if I'd explored more.", 3),
      option('C', 'Regretful. I abandoned interests I loved because they seemed impractical.', 4),
      option('D', 'Conflicted. I feel I spread myself too thin and never mastered anything.', 5),
      option('E', 'Grateful. My diverse experiences have given me a unique perspective.', 2),
    ],
  },
  {
    id: 'rr_q2',
    category: 'regret_reflection',
    text: 'Is there a field or craft you still think about but never pursued seriously?',
    options: [
      option('A', "No. I'm fully absorbed in what I'm doing now.", 1),
      option('B', 'One or two. I visit them as hobbies but not as serious paths.', 2),
      option('C', "Several. I feel pulled in multiple directions but haven't committed.", 4),
      option('D', "Many. I feel like I've missed entire versions of my life.", 5),
      option('E', 'I pursued most things I cared about, even if unconventionally.', 3),
    ],
  },
  {
    id: 'rr_q3',
    category: 'regret_reflection',
    text: "Do you believe it's 'too late' to start something new at your current stage?",
    options: [
      option('A', "Yes. Starting fresh would waste what I've already built.", 1),
      option('B', "Only for certain things. Some windows have closed, others haven't.", 2),
      option('C', 'No. I believe in lifelong learning and regularly start new things.', 3),
      option('D', "I don't think in terms of 'too late'\u2014I think in terms of energy and priority.", 3),
      option('E', "I feel it's too late for me specifically, though not for others.", 4),
    ],
  },
  {
    id: 'isp_q1',
    category: 'identity_self_perception',
    text: "When someone asks 'what do you do?' how do you typically answer?",
    options: [
      option('A', 'I give my job title or primary professional role.', 1),
      option('B', 'I mention my main work but feel the need to explain the other things too.', 2),
      option('C', 'I list multiple things and let them figure out the connection.', 4),
      option('D', "I struggle to answer. I don't feel any single label fits me.", 5),
      option('E', "I describe what I'm currently working on, regardless of category.", 3),
    ],
  },
  {
    id: 'isp_q2',
    category: 'identity_self_perception',
    text: 'Do your multiple interests feel like a strength, a burden, or neither?',
    options: [
      option('A', 'A strength. They give me flexibility and unique perspective.', 2),
      option('B', 'A burden. I feel scattered and wish I could focus on one thing.', 5),
      option('C', "Neither. They're just parts of my life that don't need a label.", 3),
      option('D', 'It depends on the context. Some environments reward it, others punish it.', 4),
      option('E', "I don't have enough interests for this to be a meaningful question.", 1),
    ],
  },
  {
    id: 'isp_q3',
    category: 'identity_self_perception',
    text: 'How comfortable are you claiming expertise in any of your skill areas?',
    options: [
      option('A', 'Very comfortable. I have credentials and experience to back it up.', 1),
      option('B', 'Somewhat comfortable. I know my capability even if I lack formal proof.', 2),
      option('C', 'Uncomfortable. I feel like an imposter regardless of evidence.', 5),
      option('D', "I don't think in terms of expertise. I'm always learning.", 3),
      option('E', "It varies by domain. I'm confident in some, uncertain in others.", 4),
    ],
  },
  {
    id: 'ae_q1',
    category: 'agency_energy',
    text: 'How would you describe the balance between your desire to learn and your energy to produce?',
    options: [
      option('A', 'I learn steadily and produce consistently. The balance feels natural.', 2),
      option('B', 'I learn much more than I produce. Output feels like a bottleneck.', 4),
      option('C', 'I produce well in structured contexts but struggle with personal projects.', 1),
      option('D', 'I have many unfinished projects. Starting is easier than finishing.', 5),
      option('E', 'I focus on output over learning. I refine what I know rather than expand.', 1),
    ],
  },
  {
    id: 'ae_q2',
    category: 'agency_energy',
    text: 'In the past year, how many of your skill areas have produced tangible, shareable results?',
    options: [
      option('A', 'One. I focus my output into a single, polished stream.', 1),
      option('B', 'Two to three. I maintain a small portfolio of active outputs.', 2),
      option('C', 'Several, but inconsistently. Some months active, others dormant.', 3),
      option('D', 'Many, but mostly experimental or private. Not much public sharing.', 4),
      option('E', 'Very few. I consume and learn more than I create or ship.', 5),
    ],
  },
  {
    id: 'ae_q3',
    category: 'agency_energy',
    text: 'If you had to drop all but one of your current interests, which would you keep\u2014and why?',
    options: [
      option('A', 'The one that earns my living. Practical necessity decides.', 1),
      option('B', "The one that feels most 'me'\u2014even if it's not the most useful.", 2),
      option('C', "I genuinely can't choose. They all feel essential to who I am.", 4),
      option('D', "The one that connects most of the others\u2014it's my anchor.", 3),
      option('E', "I'd rather keep two or three in reduced form than one fully.", 3),
    ],
  },
]
